### ISSUE TITLE
Problem defining settings for plugin

### ISSUE THREAD

**Issue by sayonaki-tatsu** [DoctorMcKay/HSPI_WebHookNotifications#1]
Hello.

I'm having a problem defining settings. They just revert to blanks and I'm having this error in log:
Code:
`warn: System.MissingMethodException: System.Func'5System.Net.Http.HttpClientHandler.get_DangerousAcceptAnyServerCertificateValidator() at HSPI_WebHookNotifications.HSPI.PostBackProc (System.String pageName, System.String data, System.String user, System.Int32 userRights) [0x000f3] in <50c2843d36d04fe5b8981e50b22445c9>:0`
I do realize, that it's probably not caused by any plugin specifics, since I use quite unortodox setup for controller (OpenSUSE on quite old hardware), but the thing is:
1. It worked just fine before I reinstalled the system from a scratch (because hdd malfunction)
2. All the rest including Z-Wave plugin works just fine.
3. If I remember it right, last time I've set it up plugin was in previous version

What I noticed is that there's a new setting option concerning safe/unsafe connections and I see something similar in error message. 
Do I lack some mono library with needed function?

I've also posted the same question on HS forum: https://forums.homeseer.com/forum/internet-or-network-related-plug-ins/internet-or-network-discussion/1321069-problem-defining-settings-for-webhook-notifications-plugin

**Comment by DoctorMcKay** [comment]
Yes, your mono is out of date. You may not be able to get the latest version from your distribution's repos, in which case you'll need to compile and install it yourself.

**Comment by sayonaki-tatsu** [comment]
Thank you. 
I think I'll use older version for now.
