### ISSUE TITLE
Update to new version, can't set configuration

### ISSUE THREAD

**Issue by JPStokesSr** [DoctorMcKay/HSPI_WebHookNotifications#3]
I just updated to version 2.0.7142.3656, and when i start the plugin, i get the error about configuration.  The plugin name is not a hot link, clicking on it does nothing.  How do I get to the configuration page.
![Capture](https://user-images.githubusercontent.com/17465033/64293797-61107780-cf3b-11e9-83fd-88d68a7006b0.JPG)

**Comment by JPStokesSr** [comment]
I found this error in the log
Initializing plug-in(2): WebHook Notifications Instance::Could not load file or assembly 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.STACK: Server stack trace: Exception rethrown at [0]: at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg) at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type) at HomeSeerAPI.IPlugInAPI.InitIO(String port) at Scheduler.clsHSPI.CheckInterfaces()

**Comment by JPStokesSr** [comment]
I did not intend to close this.  I still have the problem.

**Comment by DoctorMcKay** [comment]
You probably need to update mono.

**Comment by JPStokesSr** [comment]
Can you point me to the previous version of the package that I can reinstall?  I don’t see Mono as an installed package on my HomeTroller, and I would prefer to not install other products.

**Comment by DoctorMcKay** [comment]
[Here is an older version that should work for you.](https://github.com/DoctorMcKay/HSPI_WebHookNotifications/releases/tag/v1.3.7133.41704)

Is your HomeTroller based on Windows or Linux? If you're on Linux, you definitely have mono. If you're on Windows, you'll need to update .NET Framework to use v2.

**Comment by JPStokesSr** [comment]
Thanks, that worked.

 

I’m running Windows 7.  I’ll look at updating .NET.

**Comment by phantomBit** [comment]
What version of mono is needed for the V2 support?

**Comment by DoctorMcKay** [comment]
I believe mono version 5.4 or later.

**Comment by phantomBit** [comment]
Thats odd then. im getting a similar error using the docker Homeseer container.

```
warn: System.MissingMethodException: Method not found: System.Func`5 System.Net.Http.HttpClientHandler.get_DangerousAcceptAnyServerCertificateValidator() at HSPI_WebHookNotifications.HSPI.PostBackProc (System.String pageName, System.String data, System.String user, System.Int32 userRights) [0x000f3] in `<50c2843d36d04fe5b8981e50b22445c9>:0`
```

From the docker file in that project is it using 5.18

https://github.com/marthoc/docker-homeseer/blob/master/Dockerfile#L1

```
FROM mono:5.18.0.225

ENV S6_VERSION=v1.21.4.0
ENV LANG=en_US.UTF-8
ENV HOMESEER_VERSION=3_0_0_548
```
