### ISSUE TITLE
Error/Exception after installation of latest plugin version

### ISSUE THREAD

**Issue by smuskiew** [DoctorMcKay/HSPI_WebHookNotifications#5]
Hi, I'm having difficulty getting HomeSeer (HS3 ZEE S2 Edition 3.0.0.548) to install/enable the latest version of the HSPI_WebHookNotifications.  Looking at the logfile it appears to be installing OK but then when it goes to enable the plugin I see the following exception in the HS log:

<img width="986" alt="Screen Shot 2019-11-29 at 4 59 42 PM" src="https://user-images.githubusercontent.com/37269491/69891430-72fb7f80-12ca-11ea-9e76-7ee683f029ac.png">

Not sure if this is significant, but I had previous versions of the plugin installed and running but at some point I think I disabled this plugin from the Plugins > Manage page.  (Can't remember exactly but I think it might have been the 1.0 version of the plugin).

Is there something I can do in HS to fix this?  Let me know if more detail is needed here...

thanks!

**Comment by DoctorMcKay** [comment]
Unfortunately, this plugin requires a fairly new version of Mono, and the version on your HomeTroller is probably too old to support version 2 of the plugin. 

If you're familiar with SSH, you could try SSHing into your HomeTroller and running `sudo apt-get update` and then `sudo apt-get upgrade`.

**Comment by smuskiew** [comment]
Ah ok, makes sense, thanks.  Is there a minimum version of mono that is needed?  Looks like my hometroller is still on mono 4.5.1 but I'm seeing a bunch of stuff in the forums about memory leaks with mono 6.0.  Wondering if using 5.x would be sufficient or not.

Or alternatively is there a way to get an older version of WebHookNotifications installed since I know the older version was working at one point?

**Comment by smuskiew** [comment]
Nevermind, if I actually _read_ your release notes I'd have the answer to both my questions (duh!)

Thanks for the help!
